version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: c3-showcase-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: c3-showcase
      MYSQL_USER: application
      MYSQL_PASSWORD: admin123